services:
  db:
    image: postgres:15-alpine
    container_name: seiko_db
    environment:
      POSTGRES_DB: jwtauth
      POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_server
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/realm.json:ro
    ports:
      - "8080:8080"
    depends_on:
      - db

  ollama:
    image: ollama/ollama:latest
    container_name: seiko_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  backend:
    image: localhost/seiko-backend:latest
    container_name: seiko_backend
    depends_on:
      - db
      - ollama
    ports:
      - "5000:5000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: jwtauth
      OLLAMA_URL: http://seiko_ollama:11434
      OLLAMA_MODEL: llama3.2

  frontend:
    image: localhost/seiko-frontend:latest
    container_name: seiko_frontend
    depends_on:
      - backend
      - keycloak
    ports:
      - "3000:3000"
    environment:
      BROWSER: none
      CHOKIDAR_USEPOLLING: true

  adminer:
    image: adminer
    container_name: seiko_adminer
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  postgres_data:
  ollama_data:
